### ISSUE TITLE
Versionize 

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/back8sup#14]
Instead of always using `:latest` we should versionize this.

- [x]  autobuild according to tags.

**Comment by tongpu** [comment]
I've extended the autobuild configuration on Docker Hub to build on tags matching the regex `/^v[0-9.]+$/`. We'll see if it works correctly when we tag the first release.

**Comment by eyenx** [comment]
thank you!

On 22 July 2020 21:40:53 CEST, Lukas Grossar <notifications@github.com> wrote:
>I've extended the autobuild configuration on Docker Hub to build on
>tags matching the regex `/^v[0-9.]+$/`. We'll see if it works correctly
>when we tag the first release.

-- 

We are now called Adfinis! More at www.adfinis.com

Adfinis AG
Antonio Tauro, System Engineer, GPG KeyID: 0x0796132F0077A5F8
Güterstrasse 86 | CH-4053 Basel
Office +41 61 500 31 31 | Direct +41 61 500 31 37
www.adfinis.com

**Comment by eyenx** [comment]
Works. Started working on an autotag github action. see #15

--
We are now called Adfinis! More at www.adfinis.com

Adfinis AG
Antonio Tauro, System Engineer, GPG KeyID: 0x0796132F0077A5F8
Güterstrasse 86 | CH-4053 Basel
Office +41 61 500 31 31 | Direct +41 61 500 31 37
www.adfinis.com



-----Original message-----

**Comment by eyenx** [comment]
@tongpu can you do the same for [debug-container](https://github.com/adfinis-sygroup/debug-container) ? thanks

**Comment by tongpu** [comment]
> @tongpu can you do the same for [debug-container](https://github.com/adfinis-sygroup/debug-container) ? thanks

Done.
