### ISSUE TITLE
Openshift integration

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/back8sup#5]
We need a oscp integration of this container.

**Comment by eyenx** [comment]
isn't it a problem using `kubectl` instead of `oc`?

On 27 May 2020 20:38:20 CEST, Lukas Grossar <notifications@github.com> wrote:
>I believe that since the change to using the `nobody` user it should
>work in OpenShift without any changes.

-- 

We are now called Adfinis! More at www.adfinis.com

Adfinis AG
Antonio Tauro, System Engineer, GPG KeyID: 0x0796132F0077A5F8
Güterstrasse 86 | CH-4053 Basel
Office +41 61 500 31 31 | Direct +41 61 500 31 37
www.adfinis.com

**Comment by tongpu** [comment]
> isn't it a problem using `kubectl` instead of `oc`?

Since all custom OpenShift APIs have been converted to Cards (at least I think so) it shouldn't make a difference anymore. Especially with the approach to backup we're using here (explicit object selection instead of dumping everything).

**Comment by eyenx** [comment]
Good. I guess @s3lph could be the first to try this out on a oscp 4.x cluster. 



On 27 May 2020 21:47:59 CEST, Lukas Grossar <notifications@github.com> wrote:
>> isn't it a problem using `kubectl` instead of `oc`?
>
>Since all custom OpenShift APIs have been converted to Cards (at least
>I think so) it shouldn't make a difference anymore. Especially with the
>approach to backup we're using here (explicit object selection instead
>of dumping everything).

-- 

We are now called Adfinis! More at www.adfinis.com

Adfinis AG
Antonio Tauro, System Engineer, GPG KeyID: 0x0796132F0077A5F8
Güterstrasse 86 | CH-4053 Basel
Office +41 61 500 31 31 | Direct +41 61 500 31 37
www.adfinis.com

**Comment by s3lph** [comment]
It basically does work, however, due to the different permission model used in Openshift (pods running as random UIDs and GID=0), the kubectl client in the container can't write the API cache to `~/.kube/cache`, so each API call is utterly slow.

**Comment by s3lph** [comment]
As a workaround until this is merged, I'm using an OpenShift BuildConfig with the following Dockerfile:
```Dockerfile
FROM docker.io/adfinissygroup/back8sup:latest
USER 0
RUN mkdir -p /workdir && chgrp 0 -R /workdir && chmod g=u -R /workdir
ENV HOME /workdir
WORKDIR /workdir
USER 65534
```
