### ISSUE TITLE
Non-namespaced resources are exported once per namespace

### ISSUE THREAD

**Issue by s3lph** [adfinis-sygroup/back8sup#7]
### Version Info
* **Image Version**: `docker.io/adfinissygroup/back8sup@sha256:b2f89aa4e581d7d3ff7f5328763c3e819bd7c517339fe373ad1a3925fb46799f` (`latest` as of 2020-06-19)
* **Kubernetes Version**: 1.16.2 (OpenShift 4.3.8)

### Expected behavior
Non-namespaced resources are dumped only once.

### Actual behavior
This script dumps non-namespaced resources (e.g. PersistentVolumes) once per namespace.

**Comment by eyenx** [comment]
#11 should have fixed this. can you confirm?

**Comment by eyenx** [comment]
Waiting for #10

**Comment by eyenx** [comment]
Should been fixed with #10 and #11 please test @s3lph 

`adfinissygroup/backup:v0.1.4`

**Comment by s3lph** [comment]
Tested, fixed.
